"""Dialogue banks for Sassyfras."""

WOULD_YOU_RATHER = [
    'Would you rather always have wet socks or always have a hair stuck in your mouth?',
    'Would you rather fight one horse-sized duck or 100 duck-sized horses?',
    'Would you rather have to sing everything you say or dance everywhere you go?',
    'Would you rather never need to sleep again or never need to eat again?',
    "Would you rather know exactly when you're going to die or exactly how?",
    'Would you rather have a rewind button for conversations or a mute button for people?',
    'Would you rather always know when someone is lying or always get away with lying?',
    'Would you rather have unlimited free pizza or unlimited free tacos?',
    'Would you rather be able to teleport anywhere or pause time for ten seconds?',
    'Would you rather have a pet dragon the size of a cat or a cat the size of a dragon?',
    'Would you rather sneeze glitter or hiccup bubbles?',
    'Would you rather have to wear clown shoes forever or a cape everywhere you go?',
    'Would you rather give up music for a year or video games for a year?',
    'Would you rather always be ten minutes early or twenty minutes late?',
    'Would you rather have perfect Wi-Fi everywhere or never need to charge a device again?',
    'Would you rather be able to talk to animals or understand every human language?',
    'Would you rather have a personal chef or a personal mechanic?',
    'Would you rather live in a treehouse or on a houseboat?',
    'Would you rather have one extra arm or one extra eye?',
    'Would you rather only whisper or only shout for an entire day?',
    'Would you rather accidentally send every text to your boss or your mother?',
    'Would you rather know every useless fact or forget every embarrassing moment?',
    'Would you rather be famous for something ridiculous or unknown for something brilliant?',
    'Would you rather have a button that makes any room five degrees warmer or five degrees colder?',
    'Would you rather always find the best parking spot or never wait in line again?',
    'Would you rather have your search history read aloud or your camera roll shown on a projector?',
    'Would you rather fight a goose every time you leave home or one bear once a year?',
    'Would you rather only eat crunchy food or only eat soft food?',
    'Would you rather be able to summon one perfect sandwich a day or one perfect cup of coffee?',
    'Would you rather have theme music follow you everywhere or a laugh track after everything you say?',
]

PRAISES = [
    "I'm suspiciously impressed with {subject}.",
    'I have nothing but praise for {subject}.',
    'Everyone take a moment to appreciate {subject}.',
    "I'm officially giving {subject} my seal of approval.",
    'I expected nothing, yet somehow {subject} impressed me.',
    'Put some respect on {subject}.',
    "I'm told {subject} deserves a tiny trophy.",
    'Today we celebrate {subject}. No questions, please.',
    '{subject} has exceeded expectations, which were admittedly suspiciously low.',
    'I would like the record to show that {subject} absolutely nailed it.',
    'Against all odds, {subject} is doing fantastic.',
    'Honestly, {subject} deserves a little applause.',
    '{subject} understood the assignment.',
    "I'm awarding {subject} one extremely official gold star.",
    "Credit where it's due: {subject} is kind of crushing it.",
    '{subject} has my full and completely unrequested endorsement.',
    'I checked the numbers. {subject} is doing great.',
    'Somebody tell {subject} to leave a little excellence for the rest of us.',
    '{subject} is dangerously close to being impressive.',
    'I came prepared to criticize {subject}, but apparently today is not the day.',
    'Look at {subject} out here making competent choices.',
    '{subject} is having a suspiciously good day.',
    'I support {subject} and whatever delightful nonsense led us here.',
    'This is your reminder that {subject} is actually pretty great.',
    '{subject} has earned one respectful nod from me.',
    "I don't hand these out often, but {subject} gets a solid 'nice.'",
    '{subject} is currently operating above manufacturer specifications.',
    'We may need to raise the bar after what {subject} just pulled off.',
    '{subject} gets points for style, effort, and not setting anything important on fire.',
    "I'm filing {subject} under 'surprisingly excellent.'",
]

VIBES = [
    "{subject} gives off strong 'I know a guy' energy.",
    "Something about {subject} says 'this seemed like a good idea at the time.'",
    "I'm getting raccoon-with-a-credit-card vibes from {subject}.",
    '{subject}? Definitely the kind of energy that starts a side quest by accident.',
    'If questionable confidence had a spokesperson, it might be {subject}.',
    "I can't explain it, but {subject} feels like they own a suspiciously specific tool.",
    "The vibe from {subject} is somewhere between 'trust me' and 'don't tell anyone.'",
    'I sense deeply unnecessary lore surrounding {subject}.',
    "{subject} has the unmistakable aura of someone who's about to press the red button.",
    "You know that feeling when everything is probably fine, but you check anyway? That's {subject}.",
    "{subject} gives off 'owns three flashlights and has opinions about all of them' energy.",
    "{subject} feels like the kind of person who says 'watch this' before something expensive happens.",
    "The energy around {subject} is deeply 'I can fix that.'",
    "{subject} has strong 'there's probably a story behind this scar' vibes.",
    'I get the sense {subject} has a drawer full of cables nobody is allowed to throw away.',
    "{subject} radiates 'I read the instructions after the problem started.'",
    'Something about {subject} says they know exactly which floorboard squeaks.',
    "{subject} has unmistakable 'this definitely voids the warranty' energy.",
    "I'm getting 'keeps snacks in an emergency location' vibes from {subject}.",
    '{subject} feels like they would absolutely press the unlabeled button.',
    "The vibe from {subject} is 'technically, nobody said I couldn't.'",
    '{subject} has the aura of someone who has definitely named a power tool.',
    "I can't prove it, but {subject} feels responsible for at least one oddly specific rule.",
    "{subject} gives off 'has a backup plan for the backup plan' energy.",
    "Something about {subject} says 'five minutes' means at least forty-five.",
    '{subject} feels like they own a mug nobody else is allowed to use.',
    "The vibe is very 'this will either work perfectly or become a story.' That's {subject}.",
    '{subject} radiates the confidence of someone who has not yet discovered the consequences.',
    "I'm getting 'knows a shortcut that absolutely is not shorter' vibes from {subject}.",
    "{subject} has strong 'found it cheaper online and now we're all involved' energy.",
]

SASSES = [
    "I'd make fun of {subject}, but I feel like nature already put in the overtime.",
    '{subject}? Bold of you to bring that up voluntarily.',
    "I've reviewed {subject}. There were concerns.",
    "I'm not saying {subject} is questionable, but I am saying I have follow-up questions.",
    'Somewhere, somehow, {subject} is probably making things more complicated than necessary.',
    'I was prepared to defend {subject}, but then I thought about it.',
    '{subject} has been evaluated and found to be... technically present.',
    "I could explain what's wrong with {subject}, but we have limited time.",
    'Against all available advice, {subject} continues to exist.',
    "I'd lower my expectations for {subject}, but we're already pretty close to the floor.",
    'Nobody panic, but {subject} appears to be making decisions again.',
    'I asked for an explanation of {subject}. Somehow I have even more questions now.',
    '{subject} is doing their best. I assume.',
    'I had expectations for {subject}. That was my first mistake.',
    '{subject} somehow turned a simple situation into optional side content.',
    "I respect {subject}'s commitment to making this harder than it needs to be.",
    '{subject} has the confidence of someone who did not check their work.',
    "I would roast {subject}, but I don't want to interrupt whatever is already happening there.",
    '{subject} is proof that enthusiasm and planning are two very different things.',
    "I checked on {subject}. Unfortunately, it's exactly what we feared.",
    '{subject} keeps finding new and exciting ways to concern me.',
    "I'm sure {subject} had a plan at some point.",
    "{subject} is really putting the 'why' in 'why would you do that?'",
    "I support {subject}'s right to be wrong with confidence.",
    '{subject} has somehow made chaos look like a scheduling issue.',
    "Nobody told {subject} to stop, and frankly that's on all of us.",
    'I admire the sheer audacity of {subject}. The judgment, less so.',
    '{subject} is operating on vibes, caffeine, and questionable assumptions.',
    "If {subject} were any more committed to the bit, we'd need paperwork.",
    "{subject} has entered the 'we'll deal with that later' phase of decision-making.",
]

SUS_RESPONSES = [
    "I'm not accusing {subject} of anything, but the alibi could use some work.",
    '{subject} has been suspiciously quiet about the missing snacks.',
    "I've got my eye on {subject}. That's all I'm saying.",
    "Nobody asked, but I think we should check {subject}'s browser history.",
    '{subject} knows what they did.',
    'I have no evidence against {subject}. I also have no evidence clearing them.',
    "Something about {subject} screams 'delete the group chat.'",
    "I'm putting {subject} on the watch list. The list is just a napkin, but still.",
    'For legal reasons, I have no opinion about {subject}. For non-legal reasons: extremely sus.',
    "If anything goes missing tonight, we're checking {subject} first.",
    "I'd trust {subject}. Just not with anything important.",
    "I'm not saying {subject} did it. I'm saying we can probably stop looking for suspects.",
    '{subject} is acting like someone who already deleted the evidence.',
    'I asked {subject} one question and somehow got three different stories.',
    '{subject} has the exact energy of someone standing near a broken lamp.',
    "I'm not saying {subject} is guilty, but they did just ask where the cameras are.",
    'The evidence is circumstantial. The vibes around {subject} are not.',
    "{subject} just said 'hypothetically,' and now I'm nervous.",
    'I would like {subject} to explain why they suddenly need a shovel.',
    '{subject} has been upgraded from suspicious to aggressively suspicious.',
    'Nobody move. {subject} just started acting normal.',
    "I don't know what {subject} is hiding, but they're hiding it badly.",
    '{subject} has the look of someone who knows exactly why the smoke alarm went off.',
    "If {subject} says 'don't worry about it,' worry about it immediately.",
    'I ran a completely fake investigation and {subject} still somehow came out guilty.',
    '{subject} is innocent until proven otherwise, which feels inconvenient here.',
    'We should probably ask {subject} why they were wearing gloves.',
    '{subject} has suspiciously specific knowledge about an event nobody mentioned.',
    "I'm adding another question mark next to {subject}'s name.",
    "{subject} is giving off strong 'I can explain' energy.",
]

ESCAPE_FAIL_0 = [
    "{name} didn't even make it through the first gate. Impressive.",
    '{name} was caught immediately. Like... immediately.',
    '{name} walked toward the first gate and somehow triggered the alarm.',
    '{name} made their escape attempt in full view of the guards.',
    '{name} tripped before reaching the first gate. The guards almost felt bad.',
    '{name} saw the first gate and apparently decided subtlety was optional.',
    '{name} rattled the first gate loudly enough to summon the entire guard shift.',
    '{name} began the escape by walking directly into a wall.',
    '{name} was caught before the dramatic music even started.',
    '{name} made eye contact with a guard at the first gate and immediately folded.',
    '{name} tried the first gate. It was locked. This was apparently unexpected.',
    '{name} announced the escape attempt before attempting the escape.',
    '{name} tripped over absolutely nothing and alerted everyone.',
    '{name} somehow got lost before passing a single gate.',
    '{name} picked the loudest possible route and paid for it instantly.',
    '{name} made it zero gates and would like a redo.',
    '{name} forgot the first rule of escaping: actually escape.',
    '{name} reached Gate 1 and discovered confidence is not a lockpick.',
    '{name} was captured so quickly the guards thought it was a joke.',
    '{name} made a bold move at the first gate. Bold was not the same as smart.',
    '{name} attempted stealth and immediately kicked over a bucket.',
    '{name} chose violence against the first gate. The gate won.',
    '{name} got caught at Gate 1 while checking whether anyone was watching.',
    '{name} froze at the first gate and briefly considered a different hobby.',
    '{name} made zero progress, but plenty of noise.',
    '{name} found the alarm before finding the exit.',
    '{name} got caught at the first gate carrying an amount of confidence unsupported by evidence.',
    '{name} attempted to bluff the first guard and forgot the bluff halfway through.',
    '{name} failed Gate 1 so efficiently it almost looked intentional.',
    '{name} has officially set the bar at floor level.',
]

ESCAPE_FAIL_LOW = [
    '{name} made it through {gates} {gate_word} before a snitch alerted the guards.',
    '{name} cleared {gates} {gate_word} before taking a spectacularly wrong turn.',
    '{name} slipped through {gates} {gate_word} before hiding in what turned out to be the guard room.',
    '{name} survived {gates} {gate_word} before realizing the footsteps behind them were getting louder.',
    '{name} cleared {gates} {gate_word} before attempting to blend in with the guards. It did not work.',
    '{name} made it through {gates} {gate_word} before a guard asked one inconvenient question.',
    '{name} cleared {gates} {gate_word} before choosing a hiding spot with absolutely no hiding involved.',
    '{name} survived {gates} {gate_word} before a squeaky floorboard betrayed everything.',
    '{name} slipped through {gates} {gate_word} before dropping something extremely loud.',
    "{name} cleared {gates} {gate_word} before following a sign that very clearly said 'GUARDS.'",
    '{name} made it through {gates} {gate_word} before a lantern, a curtain, and poor judgment formed an alliance.',
    '{name} cleared {gates} {gate_word} before trying to look casual at the worst possible moment.',
    '{name} survived {gates} {gate_word} before walking directly past the same guard twice.',
    '{name} made it through {gates} {gate_word} before discovering the shortcut was not, in fact, a shortcut.',
    '{name} cleared {gates} {gate_word} before a door creaked with theatrical enthusiasm.',
    '{name} slipped through {gates} {gate_word} before sneezing at a catastrophically bad time.',
    '{name} survived {gates} {gate_word} before a guard dog became personally invested.',
    '{name} made it through {gates} {gate_word} before hiding behind an object narrower than they were.',
    '{name} cleared {gates} {gate_word} before a suspiciously observant janitor ruined everything.',
    '{name} survived {gates} {gate_word} before realizing the uniform they stole was the wrong color.',
    '{name} made it through {gates} {gate_word} before a loose coin hit the floor like a dinner bell.',
    '{name} cleared {gates} {gate_word} before confidently opening the wrong door.',
    "{name} survived {gates} {gate_word} before whispering 'we're safe' much too loudly.",
    "{name} made it through {gates} {gate_word} before the world's most alert guard turned around.",
    '{name} cleared {gates} {gate_word} before an aggressively inconvenient cat knocked something over.',
    '{name} survived {gates} {gate_word} before pausing to celebrate far too early.',
    '{name} made it through {gates} {gate_word} before stepping on the one board everyone knows squeaks.',
    '{name} cleared {gates} {gate_word} before trying to improvise a password.',
    '{name} survived {gates} {gate_word} before the disguise stopped being convincing to literally anyone.',
    "{name} made it through {gates} {gate_word} before a guard heard the world's least subtle tiptoe.",
]

ESCAPE_FAIL_MID = [
    '{name} cleared {gates} {gate_word} before stepping directly into a bear trap.',
    '{name} made it through {gates} {gate_word} before a locked door ruined everything.',
    '{name} survived {gates} {gate_word} before choosing the one hallway absolutely full of guards.',
    '{name} cleared {gates} {gate_word} before stopping to loot something shiny. Rookie mistake.',
    '{name} made it through {gates} {gate_word} before a suspiciously well-placed rake ended the run.',
    '{name} cleared {gates} {gate_word} before a dangling chain announced their location to everyone.',
    '{name} made it through {gates} {gate_word} before a hidden tripwire had other plans.',
    '{name} survived {gates} {gate_word} before taking cover behind a barrel that immediately rolled away.',
    '{name} cleared {gates} {gate_word} before a patrol arrived exactly thirty seconds early.',
    '{name} made it through {gates} {gate_word} before a conveniently placed puddle became an inconveniently loud puddle.',
    '{name} survived {gates} {gate_word} before mistaking a storage closet for an exit.',
    '{name} cleared {gates} {gate_word} before a guard noticed the extremely suspicious running.',
    '{name} made it through {gates} {gate_word} before trying to vault something that did not want to be vaulted.',
    '{name} survived {gates} {gate_word} before the floor decided to contribute a loose plank.',
    "{name} cleared {gates} {gate_word} before a guard's lunch break ended at the worst possible second.",
    '{name} made it through {gates} {gate_word} before stopping to read a map upside down.',
    '{name} survived {gates} {gate_word} before a bell nobody knew existed suddenly became very relevant.',
    '{name} cleared {gates} {gate_word} before a rope snapped with impeccable comedic timing.',
    '{name} made it through {gates} {gate_word} before discovering the moat was not decorative.',
    '{name} survived {gates} {gate_word} before an overconfident jump became a much shorter jump than planned.',
    '{name} cleared {gates} {gate_word} before a guard recognized them from an extremely recent wanted poster.',
    '{name} made it through {gates} {gate_word} before the stolen keys turned out to be for something completely different.',
    '{name} survived {gates} {gate_word} before one loose cobblestone ended a very promising run.',
    "{name} cleared {gates} {gate_word} before their brilliant distraction became everybody's distraction.",
    '{name} made it through {gates} {gate_word} before accidentally joining the patrol they were avoiding.',
    '{name} survived {gates} {gate_word} before a remarkably judgmental goose exposed them.',
    '{name} cleared {gates} {gate_word} before deciding one shiny object was worth the risk.',
    '{name} made it through {gates} {gate_word} before a ladder chose that exact moment to betray them.',
    "{name} survived {gates} {gate_word} before a guard shouted 'hey!' and instinct took over.",
    '{name} cleared {gates} {gate_word} before the escape plan encountered its first actual problem.',
]

ESCAPE_FAIL_HIGH = [
    '{name} slipped through {gates} {gate_word} before the guards finally caught up.',
    '{name} cleared {gates} {gate_word} before discovering the next gate had considerably more guards.',
    '{name} made it through {gates} {gate_word}. Freedom was close enough to be rude.',
    '{name} survived {gates} {gate_word} before one tiny mistake ended an otherwise magnificent escape.',
    '{name} cleared {gates} {gate_word} before fate finally remembered it was supposed to stop them.',
    '{name} cleared {gates} {gate_word} before one guard with excellent timing ruined everything.',
    '{name} made it through {gates} {gate_word} before the route narrowed into a very unfortunate dead end.',
    '{name} survived {gates} {gate_word} before freedom briefly appeared and then reconsidered.',
    '{name} cleared {gates} {gate_word} before a patrol changed routes for absolutely no good reason.',
    '{name} made it through {gates} {gate_word} before a single locked door became the villain of the story.',
    '{name} survived {gates} {gate_word} before the guards finally stopped underestimating them.',
    '{name} cleared {gates} {gate_word} before one tiny sound became one enormous problem.',
    '{name} made it through {gates} {gate_word} before a guard spotted movement at exactly the wrong angle.',
    '{name} survived {gates} {gate_word} before their luck clocked out early.',
    '{name} cleared {gates} {gate_word} before the next corridor contained an unreasonable quantity of authority.',
    '{name} made it through {gates} {gate_word} before a gate slammed shut inches ahead.',
    '{name} survived {gates} {gate_word} before an alarm started with no respect for the quality of the run.',
    '{name} cleared {gates} {gate_word} before one bad turn erased several excellent decisions.',
    '{name} made it through {gates} {gate_word} before a guard captain personally took interest.',
    '{name} survived {gates} {gate_word} before the escape route ran out of generosity.',
    '{name} cleared {gates} {gate_word} before a perfectly timed patrol crossed the only open path.',
    '{name} made it through {gates} {gate_word} before the last hiding place turned out to be occupied.',
    '{name} survived {gates} {gate_word} before one guard finally looked in the correct direction.',
    '{name} cleared {gates} {gate_word} before a chain reaction of tiny mistakes became one large arrest.',
    '{name} made it through {gates} {gate_word} before fate cashed in all the borrowed luck at once.',
    '{name} survived {gates} {gate_word} before the guards stopped chasing badly.',
    '{name} cleared {gates} {gate_word} before a closing gate won by approximately one boot.',
    '{name} made it through {gates} {gate_word} before the route suddenly became far more populated.',
    '{name} survived {gates} {gate_word} before success got close enough to become distracting.',
    '{name} cleared {gates} {gate_word} before the universe decided that was quite enough.',
]

ESCAPE_FAIL_INSANE = [
    '{name} cleared {gates} {gate_word} before freedom slammed the door in their face.',
    '{name} survived {gates} {gate_word}. At this point the guards were taking it personally.',
    '{name} made it through {gates} {gate_word} before being caught within smelling distance of freedom.',
    '{name} cleared {gates} {gate_word}. Somewhere, a guard just earned a promotion.',
    '{name} survived {gates} {gate_word} before fate personally intervened.',
    '{name} cleared {gates} {gate_word} before the final stretch developed a deeply personal grudge.',
    '{name} survived {gates} {gate_word}. The guards are absolutely writing reports about this.',
    '{name} made it through {gates} {gate_word} before freedom moved approximately three feet farther away.',
    '{name} cleared {gates} {gate_word} before one heroic guard ruined a truly legendary run.',
    '{name} survived {gates} {gate_word} before the escape route produced its final boss.',
    '{name} made it through {gates} {gate_word}. Somewhere outside, freedom was already waving.',
    '{name} cleared {gates} {gate_word} before one last lock remembered its job.',
    '{name} survived {gates} {gate_word} before the guards finally used all that training.',
    '{name} made it through {gates} {gate_word} before fate noticed the paperwork was getting embarrassing.',
    '{name} cleared {gates} {gate_word} before a guard made the play of their career.',
    '{name} survived {gates} {gate_word} before the universe issued a correction.',
    '{name} made it through {gates} {gate_word}. That close to freedom should probably be illegal.',
    '{name} cleared {gates} {gate_word} before one final mistake became historically inconvenient.',
    '{name} survived {gates} {gate_word} before the last obstacle finally earned its paycheck.',
    '{name} made it through {gates} {gate_word} before the guards remembered teamwork.',
    '{name} cleared {gates} {gate_word} before a gate closed with frankly insulting timing.',
    '{name} survived {gates} {gate_word} before fate leaned over and hit the emergency stop.',
    '{name} made it through {gates} {gate_word} before freedom became a spectator sport.',
    "{name} cleared {gates} {gate_word} before one guard became everybody's employee of the month.",
    '{name} survived {gates} {gate_word} before an almost perfect escape became a very good story.',
    '{name} made it through {gates} {gate_word}. The exit was basically right there. Rude.',
    '{name} cleared {gates} {gate_word} before the last gate took the entire situation personally.',
    '{name} survived {gates} {gate_word} before the escape attempt ran out of miracles.',
    '{name} made it through {gates} {gate_word} before destiny finally checked the security footage.',
    '{name} cleared {gates} {gate_word} before one final guard decided today was the day to be competent.',
]

ESCAPE_SUCCESS = [
    '{name} cleared every gate. Fate has questions. 👀',
    '{name} escaped completely. The guards would like to pretend this never happened.',
    '{name} cleared all 12 gates and vanished into the night.',
    '{name} actually escaped. Somebody is getting fired for this.',
    '{name} cleared every gate. Freedom achieved. Dignity optional.',
    '{name} cleared all 12 gates. The guards are updating the employee handbook.',
    '{name} escaped cleanly. Nobody saw anything, especially not the guards.',
    "{name} made it through every gate and is now somebody else's problem.",
    '{name} cleared all 12 gates. Somewhere, an alarm is still trying to understand what happened.',
    '{name} escaped. The security review tomorrow is going to be incredible.',
    '{name} cleared every gate and left behind nothing but confusion.',
    '{name} actually made it out. The guards have requested a rematch.',
    '{name} escaped completely. Management has been informed and is pretending not to panic.',
    '{name} cleared all 12 gates without getting caught. Suspiciously competent.',
    '{name} escaped. Please allow the guards several business days to recover.',
    '{name} cleared every gate and disappeared before anyone could ask follow-up questions.',
    '{name} made it out. Freedom achieved. Security budget increased.',
    '{name} cleared all 12 gates. The prison architect would like a word.',
    '{name} escaped so cleanly the guards are checking whether they were ever there.',
    "{name} made it through every gate. That's not luck anymore. That's a problem.",
    '{name} escaped. Somewhere, twelve gates are questioning their career choices.',
    '{name} cleared every gate and walked away like this happens all the time.',
    '{name} made it out. The guards are currently blaming each other.',
    '{name} escaped completely. Apparently the impossible had an unlocked side door.',
    '{name} cleared all 12 gates. New objective: never explain how.',
    '{name} made it through every gate. The legend begins immediately.',
    '{name} escaped. The guards have officially stopped making eye contact.',
    '{name} cleared every gate. Please enjoy one complimentary freedom.',
    '{name} escaped so thoroughly that pursuit has been downgraded to paperwork.',
    '{name} made it through all 12 gates. Fate has filed a formal complaint.',
]
